import exercises from '../data/exercises.js';import map from '../data/exercise_muscles.js';import rules from '../data/calculation_rules.js';export const exById=Object.fromEntries(exercises.map(x=>[x.id,x]));const ds=x=>new Date(`${x}T12:00:00`);const wk=x=>{let d=ds(x),n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));return d.toISOString().slice(0,10)};const mon=x=>x.slice(0,7);
export const allSets=s=>s.workouts.flatMap(w=>w.exercises.flatMap(e=>e.sets.map((x,i)=>({date:w.date,workoutId:w.id,entryId:e.id,exerciseId:e.exerciseId,exercise:exById[e.exerciseId]?.name||e.exerciseId,set:i+1,weight:+x.weight||0,reps:+x.reps||0,volume:(+x.weight||0)*(+x.reps||0)}))));
export function sessionMetrics(s,id){const a=allSets(s).filter(x=>x.exerciseId===id),g={};a.forEach(x=>(g[x.date]??=[]).push(x));return Object.entries(g).sort().map(([date,sets])=>{const volume=sets.reduce((n,x)=>n+x.volume,0),maxWeight=Math.max(...sets.map(x=>x.weight),0),bestE1rm=Math.max(...sets.map(x=>x.weight*(1+x.reps/30)),0);return{date,volume,maxWeight,bestE1rm}})}
export function muscleLoads(s,range){const t=new Date().toISOString().slice(0,10),wk0=wk(t),m0=mon(t),o={},weeks=new Set();for(const w of s.workouts){if(range==='week'&&wk(w.date)!==wk0)continue;if(range==='month'&&mon(w.date)!==m0)continue;weeks.add(wk(w.date));for(const e of w.exercises)for(const x of map[e.exerciseId]||[])o[x.muscleId]=(o[x.muscleId]||0)+e.sets.length*x.coefficient}if(range==='month'&&weeks.size)for(const k in o)o[k]/=weeks.size;return o}
export function intensity(n){n=Math.max(0,n||0);for(const [max,score] of rules.muscleAnalytics.intensityBands)if(n<=max)return score;return 10}
export const bodyState=(s,r)=>Object.fromEntries(Object.entries(muscleLoads(s,r)).map(([id,n])=>[id,{intensity:intensity(n),selected:false}]));
function group(id){if(id.startsWith('chest-'))return'Chest';if(id.startsWith('triceps-'))return'Triceps';if(id.startsWith('biceps-'))return'Biceps';if(id.startsWith('forearm'))return'Forearms';if(id.startsWith('lats-'))return'Lats';if(id.startsWith('traps-'))return'Traps';if(id.startsWith('deltoid-rear'))return'Rear Delts';if(id.startsWith('shoulder-front'))return'Front Delts';if(id.startsWith('shoulder-side'))return'Side Delts';if(id.startsWith('quads-'))return'Quads';if(id.startsWith('hamstrings-'))return'Hamstrings';if(id.startsWith('gluteus-maximus'))return'Glutes';if(id.startsWith('adductors'))return'Adductors';if(id.startsWith('calves-'))return'Calves';if(id.startsWith('abs-'))return'Abs';if(id.startsWith('obliques'))return'Obliques';if(id.startsWith('lower-back'))return'Lower Back';return null}
export function muscleSummary(s,r){const o={};for(const[id,n]of Object.entries(muscleLoads(s,r))){const g=group(id);if(!g)continue;const side=id.endsWith('-left')?'l':id.endsWith('-right')?'r':'c';(o[g]??={l:0,r:0,c:0})[side]+=n}return Object.entries(o).map(([name,v])=>{const sides=(v.l>0?1:0)+(v.r>0?1:0),load=sides?(v.l+v.r)/sides:v.c;return{name,load,score:intensity(load)}}).sort((a,b)=>b.load-a.load)}
export function streak(s){const dates=[...new Set(s.workouts.map(x=>x.date))].sort(),set=new Set(dates);if(!dates.length)return{current:0,best:0};let cur=0,d=new Date();d.setHours(12,0,0,0);const today=d.toISOString().slice(0,10);const yesterday=new Date(d);yesterday.setDate(yesterday.getDate()-1);const y=yesterday.toISOString().slice(0,10);if(set.has(today)||set.has(y)){if(!set.has(today))d=yesterday;while(set.has(d.toISOString().slice(0,10))){cur++;d.setDate(d.getDate()-1)}}let best=0,run=0,last=null;for(const x of dates){run=last&&((ds(x)-ds(last))/86400000===1)?run+1:1;best=Math.max(best,run);last=x}return{current:cur,best}}
export const weekly=s=>{const now=new Date(),n=now.getDay(),start=new Date(now);start.setDate(now.getDate()-(n===0?6:n-1));return Array.from({length:7},(_,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let k=d.toISOString().slice(0,10);return{day:d.toLocaleDateString('en',{weekday:'narrow'}),count:s.workouts.filter(w=>w.date===k).length}})};
export const recs=s=>{const g=muscleSummary(s,'month');const out=[];for(const x of [{name:'Chest',title:'Focus on chest',text:'Your chest volume is light. Add 1–2 working sets next session.'},{name:'Quads',title:'Bring up your legs',text:'Leg volume is currently behind your other trained areas.'},{name:'Lats',title:'Improve back volume',text:'Your back has received relatively little work this month.'}]){const a=g.find(y=>y.name===x.name);if(a&&a.load<4)out.push(x)}return out.length?out:[{title:'Training looks balanced',text:'Your recent workload is spread across the major muscle groups.'}]};
